apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  namespace: cockroachdb
  labels:
    app.kubernetes.io/name: cockroachdb
spec:
  replicas: 1
  serviceName: cockroachdb
  selector:
    matchLabels:
      app.kubernetes.io/name: cockroachdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cockroachdb
    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:latest
        command:
        - /cockroach/cockroach
        args:
        - start-single-node
        - --insecure
        - --listen-addr=localhost:26357
        - --sql-addr=0.0.0.0:26257
        - --http-addr=0.0.0.0:8080
        - --store=/cockroach/cockroach-data
        - --cache=.25
        - --max-sql-memory=.25
        ports:
        - name: sql
          containerPort: 26257
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: cockroach-data
          mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
  - metadata:
      name: cockroach-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: cockroachdb
  labels:
    app.kubernetes.io/name: cockroachdb
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: cockroachdb
  ports:
  - name: sql
    port: 26257
    targetPort: 26257
  - name: http
    port: 8080
    targetPort: 8080
